### ISSUE TITLE
Move this package to JuliaMath?

### ISSUE THREAD

**Issue by tkelman** [JuliaMath/Sundials.jl#70]
In the interest of reducing JuliaLang's CI queue, we've been migrating a bunch of packages out to organizations, and I think this is one such package that we should move. It's not that high-traffic or all that actively maintained, I somehow became the ~~person~~ account with the largest number of commits here even though I can't remember if I ever actually used this for anything. Any objections? There's also a JuliaODE organization that this could fit under, but that currently looks like it's mostly a staging area for PR's to ODE.jl (which is another package that should move out of JuliaLang at some point). cc @mauro3

x-ref https://github.com/JuliaMath/Roadmap.jl/issues/1

**Comment by stevengj** [comment]
Sure.  This package and ODE.jl should be moved to the same place, probably?

**Comment by mauro3** [comment]
Yes, Sundials and ODE should go to the same place.  JuliaODE is indeed a work-group for @pwl and me to hash out the overhaul of ODE.jl.  Once that is finished, say in a month or two, it could be used as a group for differential equation packages.  However, JuliaMath seems equally suited.

**Comment by pwl** [comment]
There are already several packages for solving ODEs: Sundials.jl, ODE.jl, DifferentialEquations.jl, ODEInterface.jl and hopefully more coming (high order Taylor methods) and I fear we would overwhelm JuliaMath with ODE related stuff.

**Comment by tkelman** [comment]
Moved to JuliaMath for now. No reason we can't move multiple times if needed.
