### ISSUE TITLE
Sundials slow on 0.5

### ISSUE THREAD

**Issue by axsk** [JuliaMath/Sundials.jl#71]
I just started playing around with `0.5-rc2` and was excited that the speed of my rhs function easily doubled :)
But Sundials itself does really bad now, needing 9x the time and lots >20x more allocations:
``` julia
using Sundials, BenchmarkTools
@benchmark include(Pkg.dir("Sundials", "test/runtests.jl"))
```
0.4.6:
```
BenchmarkTools.Trial: 
  samples:          22
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  3.21 mb
  allocs estimate:  75805
  minimum time:     227.84 ms (0.00% GC)
  median time:      233.52 ms (0.00% GC)
  mean time:        238.09 ms (1.02% GC)
  maximum time:     275.99 ms (6.89% GC)
```
0.5-rc2:
```
BenchmarkTools.Trial: 
  samples:          3
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
  memory estimate:  61.24 mb
  allocs estimate:  441084
  minimum time:     1.77 s (0.87% GC)
  median time:      1.78 s (1.69% GC)
  mean time:        1.78 s (1.42% GC)
  maximum time:     1.79 s (1.69% GC)
```

**Comment by KristofferC** [comment]
Some profiling would be helpful to see what it is that actually got slower. Check out https://github.com/timholy/ProfileView.jl

**Comment by axsk** [comment]
I'm on it :)
Fixing the `pointer_to_array` -> `unsafe_wrap` deprecation sped up things to 360ms.

**Comment by KristofferC** [comment]
Ah, deprecations can wreck performance

**Comment by axsk** [comment]
I now tested cvode with my own problem, and 0.5 is 1.5x faster.
The above benchmark probably benchmarked code generation in the end, since the methods got overwritten on each run, due to the includes.
